### ISSUE TITLE
Encapsulation

### ISSUE THREAD

**Issue by trivialkettle** [commschamp/cc.mqttsn.libs#15]
Hi,
Do I see it correct, that encapsulation is not supported?

In the spec:
https://www.oasis-open.org/committees/download.php/66091/MQTT-SN_spec_v1.2.pdf

> 5.5 Forwarder Encapsulation

I have an forwarder and a connect from the client is responded with a "normal" CONNAK package
> 03 05 00

**Comment by arobenko** [comment]
Yes, you are correct. The forwarding encapsulation functionality is not implemented. For two reasons:

- I personally didn't need this functionality at the time of implementation and I haven't seen any practical application to it.
- I find the spec about the functionality confusing (length of the "Wireless Node ID" is not properly defined, and the reason why forwarder encapsulates message sent to a gateway is not clear).

Please properly describe your use case so I can advice on the solution. Do you use a gateway implementation from this project? If this is the case you'll probably have to implement the "facade" by yourself identifying the encapsulated packet and stripping the encapsulation framing before forwarding the data to the gateway, and for response packets wrap them in the appropriate encapsulation frame and send the data to the forwarder.

Note that this project provides a gateway functionality as the library exposing all the exchanged data to the driving application. It allows you to add any extra framing (such as forwarding encapsulation) and/or encryption if needed. 

Maybe in the future I will add extra "forwarder" that will help handle appropriate use cases once I properly understand it.

**Comment by arobenko** [comment]
I see. After some consideration I came to conclusion that the job of the
forwarder is to be a mini gateway for multiple clients before the actual
gateway, such as managing multiple wireless clients and forwarding their
traffic to the gateway in the single communication channel.

To properly support your use case you need to use the gateway as a library,
not as binary. You need to implement the data parsing yourself and strip
the forwarder framing. The latter contains id of the client, use it to
identify the Session object. If it's new connection create a new Session
object and retain it for the future messages. Forward the stripped MQTT-SN
message to the relevant Session object. When the Session object reports
data to be sent out, wrap it in the appropriate forwarder framing.

All the said above should not be difficult to implement. Use the current
gateway application as reference, which uses the origin ip as the session
identifier. Use your favourite event handling framework not necessarily Qt.

Unfortunately I'm too busy with other things and won't come around to
supporting forwarding functionality in the next several months.

Hope it helps

**Comment by arobenko** [comment]
On the second thought, for your specific use case, why don't you run the
gateway instead of the forwarder on the host with the BT dongle? Note that
the gateway doesn't necessarily need to run on the same machine with the
MQTT broker. The gateway uses TCP to talk to the broker and can be remote.

**Comment by arobenko** [comment]
Recently released version [v2.0](https://github.com/commschamp/cc.mqttsn.libs/releases/tag/v2.0) has encapsulation support in the gateway library.
